//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.PerkinElmer.Service.Gaea.Web.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldMatch
    {
        public int Id { get; set; }
        public string MatchText { get; set; }
        public Nullable<int> MatchScore { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Rule Rule { get; set; }
    }
}
