//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.PerkinElmer.Service.Gaea.Web.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pretreatment
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Expression { get; set; }
        public string ReplaceTo { get; set; }
        public int Order { get; set; }
    }
}
