//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextToolPoc.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TextToolContainer : DbContext
    {
        public TextToolContainer()
            : base("name=TextToolContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<TemplateField> TemplateFields { get; set; }
        public virtual DbSet<FieldMatch> FieldMatches { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Pretreatment> Pretreatments { get; set; }
        public virtual DbSet<Rule> Rules { get; set; }
        public virtual DbSet<FieldExpected> FieldExpecteds { get; set; }
    }
}
